imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: ru
    jonlil.ckfinder.customAuthentication: %kernel.root_dir%/JonlilCkfinder/config.php

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig', 'php']
#        assets_version: %version%
#        assets_version_format: %%s?ver=%%s
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true
    translator: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        project_title: %project_title%
    form:
        resources:
            #- 'ItBlasterAttachFileBundle:Form:attach_file_widget.html.twig'
            #- 'ItBlasterCheckboxListBundle:Form:checkbox_list_widget.html.twig'
            #- 'OhGoogleMapFormTypeBundle:Form:fields.html.twig'
            - 'SonataCoreBundle:Form:datepicker.html.twig'
            #- 'ItBlasterMainBundle:Form:fields.html.twig'
    #exception_controller: ItBlasterMainBundle:Layout:showException

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:
        - 'SonataCoreBundle'
        - 'SonataAdminBundle'
        - 'ItBlasterMainBundle'
    java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    encryption: ssl
    auth_mode:  login
#    spool:     { type: memory }

propel:
    path:       "%kernel.root_dir%/../vendor/propel/propel1"
    phing_path: "%kernel.root_dir%/../vendor/phing"
    logging:    %kernel.debug%

    build_properties:
        propel.useDateTimeClass: true
        propel.dateTimeClass: DateTime
        #propel.defaultTimeStampFormat
        #propel.defaultTimeFormat =
        #propel.defaultDateFormat =
        propel.builder.pluralizer.class: builder.util.StandardEnglishPluralizer
        propel.mysql.tableType: InnoDB
        propel.mysql.tableEngineKeyword: ENGINE
    dbal:
        driver:               %database_driver%
        user:                 %database_user%
        password:             %database_password%
        dsn:                  %database_driver%:host=%database_host%;dbname=%database_name%;charset=UTF8
        options:              {}
        attributes:           {}
        settings:
            charset:
                value:        UTF8

fos_user:
    db_driver: propel
    firewall_name: main
    user_class: FOS\UserBundle\Propel\User
    registration:
        confirmation:
            enabled: true
            from_email:
                address: %mailer_user%
                sender_name: %mailer_user_title%
        #form:
        #    type: artsofte_user_registration
    resetting:
        token_ttl: 7200
        email:
            from_email:
                address: %mailer_user%
                sender_name: %mailer_user_title%

monolog:
    channels: ['geochannel']
    handlers:
        file:
            type:   stream
            path:   "%kernel.logs_dir%/geo.log"
            channels: geochannel

sonata_admin:
    title:      CMS
#    title_logo: /bundles/artsoftemain/images/logo2.png
    templates:
        dashboard: SonataAdminBundle:Core:dashboard.html.twig
        ajax:    SonataAdminBundle::ajax_layout.html.twig

        # default actions templates, should extend a global templates
        list:    SonataAdminBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
        edit:    SonataAdminBundle:CRUD:edit.html.twig

    dashboard:
        blocks:
            # display a dashboard block
            - { position: left, type: sonata.admin.block.admin_list }

sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]

jonlil_ck_finder:
    baseDir: "%assetic.read_from%"
    baseUrl: "/uploads/"
    service: "php"

#lunetics_locale:
#    allowed_locales: %locales%
#    guessing_order:  [query, router]

#jms_i18n_routing:
#    default_locale: %locale%
#    locales: %locales%
#    strategy: prefix
#    strategy: prefix_except_default
#    strategy: custom
#    hosts:
#        ru: %domain%
#        en: en.%domain%
#    redirect_to_host: true
        # [optional] Defaults to false.

