#Список проектов пользователя
projects:
  pattern:  /projects
  defaults:
    _controller: ItBlasterMainBundle:Projects:list

#Страница конкретного проекта
project-show:
  pattern:  /projects/{project_name}
  defaults:
    _controller: ItBlasterMainBundle:Projects:show

#Страница конкретного проекта
project-add:
  pattern:  /project-add
  defaults:
    _controller: ItBlasterMainBundle:Projects:add

#Редактирование проекта
project-edit:
  pattern:  /project-edit/{project_name}
  defaults:
    _controller: ItBlasterMainBundle:Projects:edit

#Удаление проекта
project-delete:
  pattern:  /project-delete/{project_name}
  defaults:
    _controller: ItBlasterMainBundle:Projects:delete